### ISSUE TITLE
Compatibility with cover entity

### ISSUE THREAD

**Issue by ndex11** [benct/lovelace-multiple-entity-row#10]
Hi, can you add compatibility with cover entity? When I add only info with attribute then the control buttons disappear and there is state shown instead. I tried to set hide_state to true, but controls are still hidden. Thank you.
![image](https://user-images.githubusercontent.com/16918788/64899224-b6126300-d68a-11e9-8715-a7332f9473e9.png)

**Comment by benct** [comment]
Hi. Unfortunately, as you have shown, this card does not support "special" entities that normally include more complex controls, like cover entities. Implementing support for that is a major task, which I have no immediate plans of doing at the moment. Sorry.

**Comment by xekil** [comment]
Hello,
Are there changes to be expected or still not?
Thank you
