### ISSUE TITLE
HACS try to login endlessly

### ISSUE THREAD

**Issue by pesor** [benct/lovelace-multiple-entity-row#100]
HACS try to login endlessly, with the following error in the log file, looks like a typo "miltiple" somewhere. ![image](https://user-images.githubusercontent.com/3110308/94124250-0fdc6a00-fe55-11ea-8e27-c81a5f1ed11f.jpeg)

I have the cards running and the files in the right folder

**Comment by benct** [comment]
There is no typo `miltiple` in this repository, so I would suggest looking in your configuration (or HACS' configs) for this error..

**Comment by pesor** [comment]
You are right, it was a typo from my site, Sorry.
