### ISSUE TITLE
multiple-entity-row missing after 0.116b0 upgrade

### ISSUE THREAD

**Issue by fishbone-git** [benct/lovelace-multiple-entity-row#103]
Upgrading to the latest HA beta, my mutilple-entity-row rows are missing.  They are not in the resulting html, so not a case of hidden divs, just not included at all. I cannot identify any errors in the javascript console.  There is just no reference to multiple-entity-row.js at all (others are listed as they load, however).  The entities are active in HA, and reappear if I change to standard entity rows, or other custom row module (fold-entity-row, for example).  Reverting to 0.115.6, the rows are present again.

**Comment by Toinieboy** [comment]
Same issue, closing my duplicate ticket!

**Comment by giustanca** [comment]
Same issue here.

**Comment by noxhirsch** [comment]
I've found the issue (see here https://youtu.be/6Oi__1yuL_s?t=703):
Just change in the last line from `hui-view` to `hui-masonry-view` (and delete the .js.gz file if you're doing this locally):
`})(window.LitElement || Object.getPrototypeOf(customElements.get('hui-masonry-view')));`
I'd create a PR for that, but I don't know a way to make this backwards compatible (if even possible)

**Comment by giustanca** [comment]
it works! Thank you!

**Comment by fishbone-git** [comment]
Good catch!  works great.

**Comment by Fruchuxs** [comment]
Hm I also tried this, but it doesn't work. Tried force refresh / server restart.

**Comment by Morgan34810** [comment]
It works, great job.
Don't forget to delete the .js.gz file.

**Comment by benct** [comment]
They seem to be adding this breaking change in the next version, ref. [this article](https://developers.home-assistant.io/blog/2020/09/30/customViewChanges). I'll see if I can merge in @noxhirsch's PR soon, but I'm looking at making it backwards compatible too..

**Comment by benct** [comment]
Fixed in `v3.2.1`

**Comment by Mariusthvdb** [comment]
is this compatible wit 115 too? otherwise we have to wait some....

**Comment by benct** [comment]
Yes.

**Comment by niekniek89** [comment]
Hello,

i have the same problem, my mutilple-entity-row rows are missing.
what can I do to get this working again? I have updated mutilple-entity-row to the latest version. after a restart, the result remains the same (even after deleting the cache).

**Comment by giustanca** [comment]
Try refresh the browser

**Comment by niekniek89** [comment]
> Try refresh the browser

thanks for your help. I've refreshed the browser several times, and also tested it in a private tab. also reinstalled mutilple-entity-row. after the restart of HA, mutilple-entity-row stays away
