### ISSUE TITLE
multiple-entity-row after 0.116.1

### ISSUE THREAD

**Issue by niekniek89** [benct/lovelace-multiple-entity-row#109]
Hello,

i have a problem, my mutilple-entity-row rows are missing.
what can I do to get this working again? I have updated mutilple-entity-row to the latest version. after a restart, the result remains the same (even after deleting the cache).

I've refreshed the browser several times, and also tested it in a private tab. also reinstalled mutilple-entity-row. after the restart of HA, mutilple-entity-row stays away

i have mutilple-entity-row updated from 3.0.0 to 3.3.0, after this, same problem.

**Comment by niekniek89** [comment]
I just installed home assistant on a new VM, installed HACS, installed mutilple-entity-row rows, and even with an empty home assistant VM I can't get it resolved.

**Comment by benct** [comment]
Version `3.2.1` and above should work fine after a proper reinstall or full cache clear.. What browser are you using? Are there any errors in the browser console window (F12)?

**Comment by niekniek89** [comment]
> Version `3.2.1` and above should work fine after a proper reinstall or full cache clear.. What browser are you using? Are there any errors in the browser console window (F12)?

thnx for your help.
![HA](https://user-images.githubusercontent.com/48858098/95583611-af485200-0a3c-11eb-9feb-b3d820beb56c.png)
I am using the latest version of MS Edge (chromium).
even in a private tab it doesn't work.

**Comment by camochu** [comment]
> Version `3.2.1` and above should work fine after a proper reinstall or full cache clear.. What browser are you using? Are there any errors in the browser console window (F12)?

That solved my problem. I always forget to update to last versions

**Comment by mweinelt** [comment]
All my multiple-entity-rows have disappeared as well.

I'm on `0.116.2` and neither `3.3.0` nor `3.4.0` are working.

- I see no errors on the browser console 
- I see no errors in the home-assistant log
- There is no caching involved, since I'm using the version number to prevent caching, i.e. `multiple-entity-row.js?3.4.0`.

**Comment by niekniek89** [comment]
I have exactly the same. also no errors in the browser console. I can't get it to work in any way. not even with an empty new HA / VM

**Comment by niekniek89** [comment]
anyone a solution to this problem?

**Comment by benct** [comment]
Tested all versions above `3.2.1` on HA `0.116.x`, works fine on both Chrome, Safari and Edge... not sure how to solve this when I cannot reproduce the error.

**Comment by mweinelt** [comment]
So the simplest example that I can give of a row that is missing is this:

```yaml
views:
- cards:
  - cards:
    - type: entities
      show_header_toggle: false
      entities:
      - type: custom:multiple-entity-row
        toggle: true
        entity: switch.d56cca_relay
        entities:
        - entity: sensor.d56cca_power
          name: Power

```

**Comment by camochu** [comment]
It may seem obvious but are you sure you are updating correctly?
Have you changed version number in configuration?

.../multiple-entity-row.js**?v=3.4.0**

This and replacing the file was all I needed to do

**Comment by niekniek89** [comment]
Hello,

i got it working (no idea how).
reinstalled the multiple-entity-row, and rebuilt everything.
i think the config has also changed since 3.0.0 and above.
I have never kept this up for updates.

resolved for me now.

**Comment by mweinelt** [comment]
Oh that is odd. I diffed the .js file with the release version and it still matches v3.2.0. Something is broken in my packaging then. I'm sorry for the noise.
