### ISSUE TITLE
Number precision

### ISSUE THREAD

**Issue by TH-Braemer** [benct/lovelace-multiple-entity-row#110]
If it was possible to set precision on numbers I could eliminate a ton of templates.

I would really love this feature combined with all the other nice features 👍

**Comment by julienlarivee** [comment]
It would like this too.
I sometime show input numbers and "1" is shown as "1.0"
It would be great to be able to set a precision. 
In this case I could hide the decimal.

**Comment by benct** [comment]
Version `3.5.0` now supports format option `precision<0-9>` for decimal precision (I.e. `precision2` for two decimals).

**Comment by julienlarivee** [comment]
Thanks for this modification :)

Just noticed something though.
When entering a format, the unit of measurement disappears. 
Setting a 'unit' in the card doesn't bring it back.

**Comment by benct** [comment]
Hmm, you're right.. I'll try to fix that soon.

**Comment by julienlarivee** [comment]
Everything is looking great with 117. Thank you!
