### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by ericvitale** [benct/lovelace-multiple-entity-row#120]
I use this all over my installation. I'd like to contribute to add a few new small features (if possible). I'm struggling on how to edit the component locally. Are there any instructions of how to do this?

I tried editing the /config/www/lovelace-multiple-entity-row/multiple-entity-row.js, but nothing takes, so I assume HA is caching this file somewhere and there is a proper process to follow.

I understand the whole github process for contributing, just not how to run it locally.

**Comment by benct** [comment]
Try clearing caches in your browser. Enable developer tools (F12) and set `disable cache` in the network tab. Use hard refresh when reloading changes. Make sure the path above matches what is set under `resources` in `configuration.yaml` if you are using yaml mode.

You can manually add your changed JS file to your www folder and temporarily replace the current resource url in `configuration.yaml` with `url: /local/multiple-entity-row.js?v=123456`. Adding a parameter and changing the value will override the cache if needed. Also remember to click `Reload resources` in the menu (three dots) on HA when changing the configuration file.
