### ISSUE TITLE
Label with extra info..

### ISSUE THREAD

**Issue by tane64** [benct/lovelace-multiple-entity-row#122]
Hi,
Hope you can help me with this layout.

Looking for some extra setting to make the few as the others

See the sample

![image](https://user-images.githubusercontent.com/60829997/97614449-3ffdc680-1a1a-11eb-8c5f-75af3ab8883e.png)

Werkkamer line is with standard button.
Badkamer is with multiple enity.

What i'm looking for

- Remove the first icon in from of Badkamer (it just a label)
- Make Badkamer text bigger (Like other lines)
- Display the button layout 

====
Standard
type: button
tap_action:
  action: toggle
name: Werkkamer
entity: sensor.temperature_11
show_state: true
show_icon: false

===
type: 'custom:multiple-entity-row'
name: Badkamer
show_state: false
entity: sensor.temperature_6
entities:
  - entity: sensor.humidity_7
  - sensor.temperature_6

**Comment by benct** [comment]
I'm not sure this card can do what you are wanting to do.. It's not currently possible to remove the icon or change sizes or layout directly. You could try using [card-mod](https://github.com/thomasloven/lovelace-card-mod) to modify what you like.

**Comment by tane64** [comment]
Thanks.  
Will try that.
