### ISSUE TITLE
Incorrect Secondary Info

### ISSUE THREAD

**Issue by tempod** [benct/lovelace-multiple-entity-row#123]
Hello.
I am using this great integration on my HA but I think there is a problem.

![Cattura](https://user-images.githubusercontent.com/71033514/97639146-4736cb80-1a3e-11eb-8197-2302857033b1.JPG)

In the image above you can see how the 'secondary_info' with the red line is shown correctly. The one with the green line returns an error. Instead of displaying the value, it displays the text.

If I use the card without activating the integration the 'brightness' value is shown correctly (in this second picture the light is on but that's not the problem).

![Cattura2](https://user-images.githubusercontent.com/71033514/97639714-64b86500-1a3f-11eb-9fec-56f81a321c86.JPG)

thank you

**Comment by benct** [comment]
Please read the Readme; `secondary_info` currently only supports the `last-changed` option of the defaults from HA. I'm adding support for the rest in the next release though.

Meanwhile you should be able to do something like:
```
secondary_info:
  attribute: brightness
  unit: '%'
```
