### ISSUE TITLE
show_header_togglemain

### ISSUE THREAD

**Issue by idoaflalo** [benct/lovelace-multiple-entity-row#126]
when show_header_toggle is set to true. the main toggle should turn all the switches and not only the main

**Comment by benct** [comment]
I'm not sure that is even possible as it is controlled by the HA [entities](https://www.home-assistant.io/lovelace/entities/) card and not by multiple-entity-row. Furthermore, I do not agree that is should control all toggles in the row, as people may use toggles in different ways for various other entities in this card..
