### ISSUE TITLE
support empty values when using formatting

### ISSUE THREAD

**Issue by pinkywafer** [benct/lovelace-multiple-entity-row#127]
Formatting works beautifully, as long as the value is set.  If a value has not yet been set, the formatting option will display an incorrect result: ie: 
a `datetime` format will display `January 1, 1970, 1:00am` if the state / attribute selected is None.
It would be nice if either a simple `-` or `None` could be displayed in these circumstances

**Comment by myhomeiot** [comment]
Please add support brightness option for formatting. At version 4.0.0 you add brightness support to secondary_info but in some cases more useful to have it as separate entity, for example (in my case brightness attribute it's a value from 0-255) :
```
type: 'custom:auto-entities'
card:
  type: entities
filter:
  exclude:
    - state: 'off'
  include:
    - domain: light
      attributes:
        supported_features: 1
      options:
        type: 'custom:multiple-entity-row'
        secondary_info: last-changed
        state_color: false
        toggle: true
        entities:
          - attribute: brightness
            name: false
            format: !!!brightness option will be great!!!

**Comment by benct** [comment]
Should now better handle empty or invalid values in `v4.1.0`. I've not tested it properly, so let me know if it is not working as expected.
