### ISSUE TITLE
Some attributes showing as Unavailable

### ISSUE THREAD

**Issue by kloggy** [benct/lovelace-multiple-entity-row#13]
I have a sensor for my Fully Kiosk Tablet. A lot of the attributes will not show using this card.
For example:
`screenBrightness` and
`currentPage`

I thought it might have something to do with upper case letters in the attribute name but
`SDK` and
`versionCode`
work.

My Lovelace config is like this,
```
          - type: entities
            title: '-- Hall Panel --'
            show_header_toggle: false
            entities:
              - entity: light.hallpanel
                type: custom:multiple-entity-row
                name: Screen
                icon: mdi:tablet
                info:
                  entity: sensor.hall_panel_fully_kiosk_info
                  attribute: versionCode
                  name: ' '
                primary:
                  entity: sensor.hall_panel_fully_kiosk_info
                  attribute: currentPage
                  name: 'Brightness: '
```
![image](https://user-images.githubusercontent.com/38220016/65964351-b4031f00-e454-11e9-9fe0-141a621a95af.png)

And the sensor is like this

![image](https://user-images.githubusercontent.com/38220016/65964299-8918cb00-e454-11e9-9117-93eed0cf3414.png)

**Comment by kloggy** [comment]
I just did a restart (for the new version of HACS) and one of those entities, Brightness, is now showing up... I have no idea why this should be?

![image](https://user-images.githubusercontent.com/38220016/66039687-757d6b00-e50d-11e9-92c6-705c1cbb4e65.png)

**Comment by kloggy** [comment]
I spoke too soon... now it is gone again!
![image](https://user-images.githubusercontent.com/38220016/66039762-aa89bd80-e50d-11e9-9561-f80e4903c77e.png)

It still shows as an attribute in my States page

![image](https://user-images.githubusercontent.com/38220016/66040123-95f9f500-e50e-11e9-9bf6-42bf1ded83d4.png)

I also have to apologise that I copied and pasted a testing version of my Lovelace yaml in the original post. The correct config is as follows (but the issue still seems to stand for `screenBrightness`.

```
          - type: entities
            title: '-- Hall Panel --'
            show_header_toggle: false
            entities:
              - entity: light.hallpanel
                type: custom:multiple-entity-row
                name: Screen
                icon: mdi:tablet
                info:
                  entity: sensor.hall_panel_fully_kiosk_info
                  attribute: currentPageUrl
                  name: ' '
                primary:
                  entity: sensor.hall_panel_fully_kiosk_info
                  attribute: screenBrightness
                  name: 'Brightness: '
```

**Comment by kloggy** [comment]
OK, sorry for the multiple posts but I think I have found the issue. It *appears* that the card is not displaying the value when it is 0 because it showed again when it went to 255.

**Comment by benct** [comment]
Good catch, I think there is some bad falsy check (the number 0 results in false, which makes it not display) that I have missed in the code. Will try to fix this asap.

**Comment by benct** [comment]
Should be fixed in the latest version.

**Comment by kloggy** [comment]
Yes... Looks like it is! Thank you.
