### ISSUE TITLE
Smaller font options for secondary_info

### ISSUE THREAD

**Issue by rradar** [benct/lovelace-multiple-entity-row#130]
Hey there!
Very nice card you have here :tada:

It would be even nicer if there would be a option to have a smaller font (e.g. like the state header) for the secondary_info.

So in this example the battery :battery: percentages would be shown less prominent:
![image](https://user-images.githubusercontent.com/34582688/98278285-477c1d00-1f90-11eb-9dd5-db2f9bbec821.png)

**Comment by benct** [comment]
The left part of the entity row is handled by HA's default generic row, so it will not be easily possible to support in this card. However, you should be able to use [card-mod](https://github.com/thomasloven/lovelace-card-mod) to modify these styles.
