### ISSUE TITLE
Support duration like option for formatting which shows days

### ISSUE THREAD

**Issue by myhomeiot** [benct/lovelace-multiple-entity-row#132]
Duration option is not useful for long running equipment, it's shows `hours:minutes:seconds` so for 9 days it's will show something like 216:23:51.
New or modified duration option should count days and show `days:hours:minutes:seconds` or even something better like `9d 23h 51m 28s` or maybe custom formatted - all depends from complexity of implementation and amount of changes required at plugin code.
Thanks for your efforts!

`relative` and `total` (BTW i'ts not included in [documentation](https://github.com/benct/lovelace-multiple-entity-row#formatting) but it's works) doesn't show it's correctly, for example 9 days shows as `1 week`.

**Comment by benct** [comment]
The card is using a common function for calculating duration from [custom-card-helpers](https://github.com/custom-cards/custom-card-helpers) which does not support `days`. Not really sure I want to create some custom implementation just for showing days.. 

(Options `relative` and `total` is handled by HA's relative time element and correctly shows timestamps as week, days, etc)

**Comment by myhomeiot** [comment]
Duration doesn't work in 4.4.1 nor in few previous releases which has other problem.

**Comment by fusionstream** [comment]
A fair number of devices also use 'seconds' as their timestamp. Perhaps the ability to subtract this number from unixtime and then format it as relative/total would be good?
