### ISSUE TITLE
"styles" for the main entity: cannot change icon's color

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#143]
For secondary entities it is possible to change a color of icon:
```
styles:
  '--paper-item-icon-color': cyan
```
But not for the main entity (((
Have to use card-mod.

**Comment by benct** [comment]
That's correct, as the readme says: "Add custom CSS styles to the **state element**". The icon and name is rendered by HA's generic entity row element and is more complicated to change.
