### ISSUE TITLE
Centering, margin and sizing options

### ISSUE THREAD

**Issue by TomTorger** [benct/lovelace-multiple-entity-row#146]
Great work! I really like it 👍 

I was going to use this to display my living room lighting scene sets. However, I cannot get the buttons to fit well on other platforms than mobile (pc, pad).

What I am missing are options for padding/margins, adjusting the icon sizes (too small for my fingers), and also centering.:

![image](https://user-images.githubusercontent.com/49571281/99880947-ed798980-2c16-11eb-8f6f-f7bf7e701333.png)

**Comment by benct** [comment]
Try the `styles` option? If that does not work for you, you'll have to use [card-mod](https://github.com/thomasloven/lovelace-card-mod).

```
styles:
  width: 80px
  padding: 5px
```
