### ISSUE TITLE
Can we add "Custom styles option on secondary info" back :) 

### ISSUE THREAD

**Issue by skynet01** [benct/lovelace-multiple-entity-row#147]
Hi there, really used this feature a lot in my configs, any chance to bring it back? Or is there an alternative way to apply custom styles to secondary info? 

Thanks so much, love this plugin!

**Comment by benct** [comment]
Sorry but HA's generic entity row element handles this part now, so it's not (easily) possible to implement styling on the secondary info.. would recommend using [card-mod](https://github.com/thomasloven/lovelace-card-mod) for any additional styling needs.
