### ISSUE TITLE
multi-entity-row in vertical-stack - misalignment

### ISSUE THREAD

**Issue by baunan** [benct/lovelace-multiple-entity-row#148]
I have an issue with multi-entity-row when used in combination with vertical stack. For some reason the row is getting stretched compared to when used in an entities card. Is this something that be corrected as it makes the multi-entity-row misaligned vertically compare to other rows in a vertical-stack card? 
I have attached 3 pictures, the first is the row in the entities card, the second in the vertical-stack card and the last is multi-entiti-row together with other entity in a vertical-stack card, where the misalignment can be seen.

![image](https://user-images.githubusercontent.com/59838425/100269051-3d798880-2f56-11eb-8714-dc7992d6caa9.png)
![image](https://user-images.githubusercontent.com/59838425/100269085-49fde100-2f56-11eb-96c2-8196c92d6940.png)
![image](https://user-images.githubusercontent.com/59838425/100270512-76b2f800-2f58-11eb-91a2-3f7735bf6b1e.png)

I am using v4.0 of the multi-entity-row addon.

**Comment by benct** [comment]
Looks like you are not using `multiple-entity-row` in a [entities](https://www.home-assistant.io/lovelace/entities/) card, which is required for proper rendering?

**Comment by baunan** [comment]
Thanks for the feedback. I thought it could be something like this that was behind it.
