### ISSUE TITLE
Add toggle for pri+sec and tertiary option

### ISSUE THREAD

**Issue by marchammer2003** [benct/lovelace-multiple-entity-row#15]
Is it possible to add the following;

- [x] A toggle for the primary and secondary objects
- [x] Name above the entity value (value at the end of the row)
- [x] A tertiary object?

Thanks :)

**Comment by benct** [comment]
Added support for an optional tertiary entity and for a name above the main entity value. Thanks for the suggestions!

As for the toggles, they will have to replace the whole element (entity) which I am afraid will look kind of messy if you have several unnamed toggles next to each other. On the other hand that depends on how you use the card and how many you define.. Not quite decided on that yet.

**Comment by marchammer2003** [comment]
My plan was to use one line (entity) for each room in the house.
The bathroom has one controlled light (main entity) and a temp. measurement (primary object) so no problems here.
The problem is e.g. the livingroom where I have 3 lights and a temp. measurement. The current code only allows me to add a toggle to one of the 3 lights (main entity) and there is no room for the temp. measurement until the tertiary object is added.

By the way, thanks for a great code and the fast responce :)

**Comment by marchammer2003** [comment]
Just tested your latest update. It would be nice to have the added `name_state` above the main entity value to be visible if the toggle option is set to `true`.

**Comment by benct** [comment]
Just pushed a new version which includes toggle support! Let me know if anything is not working as intended :)

**Comment by MrBLJ** [comment]
That's workinf quite well for me, and it's awesome ! Would it be difficult to diplay an icon instead of the Name and Toggle for each entity ? Ideally, the icon could be defined according to the state.

Thanks a lot for what you achieved so far !

**Comment by benct** [comment]
An icon (or button as it would have to be) has been suggested in #6 too, so I will try to add some support for that in a future release :)
