### ISSUE TITLE
"format: invert" support for entities

### ISSUE THREAD

**Issue by ildar170975** [benct/lovelace-multiple-entity-row#151]
Is it possible to implement a "format: invert" for entities?
"Invert" means "show a negative value as a positive one".

**Example:**
"Netdata" integration provides negative values for some statistical data like "HDD writes", "Network outgoing speed" etc.
It is very useful to have this data negative - on a graph (mini-graph-card, history-graph)  the "HDD reads" & "HDD writes" (as well as "Net in", "Net out") one graph will be shown above X-axis, second one - above:
![изображение](https://user-images.githubusercontent.com/71872483/100396672-076ffd80-3057-11eb-8f38-a89b52d70b32.png)
But it is not convenient to have these negative values on Entities card.
That is why it would be great to display these negative values inverted.

**Comment by benct** [comment]
Sorry for taking so long.. added `invert` formatting option in version `4.4.0` 🙂

**Comment by ildar170975** [comment]
Thank you very much!
