### ISSUE TITLE
Styles not wokring for secondary_info

### ISSUE THREAD

**Issue by sasukebinbin** [benct/lovelace-multiple-entity-row#153]
entities:
      - entity: binary_sensor.door_window_sensor_158d00027393c6
        state_color: true
        type: 'custom:multiple-entity-row'
        secondary_info: 
          attribute: battery_level
          styles:
            color: red  
          name: "Battery:"

**Comment by benct** [comment]
Removed in version [4.0.0](https://github.com/benct/lovelace-multiple-entity-row/releases/tag/v4.0.0). See #147.

**Comment by bjeanes** [comment]
FYI the README still has `styles:` under `secondary_info` so I spent some time trying to understand what I was doing wrong before finding this issue 😬

**Comment by bjeanes** [comment]
For others, [this post](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1190?u=bjeanes) looks to be a great resource in all the ways you can style all parts of `multiple-entity-row`.
