### ISSUE TITLE
Reqest to support markdown card

### ISSUE THREAD

**Issue by sasukebinbin** [benct/lovelace-multiple-entity-row#154]
Custom card type is supported.
But when I use type: markdown. It shows error. 

Apperaciate to make it support markdown card.

**Comment by benct** [comment]
Markdown is not supported in this card? Where/how are you trying to use this?

**Comment by sasukebinbin** [comment]
Sorry. It was lovelace-fold-entity-row not multiple-entity-row. Please ignor this.
