### ISSUE TITLE
Not showing on HACS

### ISSUE THREAD

**Issue by phrfpeixoto** [benct/lovelace-multiple-entity-row#155]
Hi! I just tried installing this through HACS, and it's not showing on my instance:

![Screen Shot 2020-12-08 at 09 37 15](https://user-images.githubusercontent.com/10242829/101484811-f7023180-3938-11eb-828e-a28a7e666c7c.png)

Trying to add the repository manually triggers a message that it is already available on the "store".

**Comment by vansoest** [comment]
Same problem here. It’s not listed in the default hacs repository.

**Comment by benct** [comment]
It's listed in the [default repo](https://github.com/hacs/default/blob/master/plugin) and should be visible. However, if you have it installed already, it does not show in the list.
