### ISSUE TITLE
Click on entity name doesn't trig "default" tap action

### ISSUE THREAD

**Issue by fabricioavil** [benct/lovelace-multiple-entity-row#16]
Hi,
I have this card installed for 6+ months and it used to trigger the default tap action clicking on the "name" ("Front camera" or "Mobile camera" in the example below) or on the icon on the left of the name (in my case, the picture from last captured video).

So, clicking on the name or icon used to play the last captured video, but something has recently changed and when I click on the name or the icon on the left, it doesn't open the screen to play the last captured video.

I saw that if I show the state (remove "hide_state: true") and click on the state (mostly "Idle" in my case), it triggers the default action, but I didn't want to show the state.

Is it a new expected behavior? Is there an option to trigger the default tap action clicking on the entity name?

Thank you!

```entities:
  - entity: camera.aarlo_front
    name: Front camera
    primary:
      entity: sensor.aarlo_captured_today_front
      name: Captured today
    type: 'custom:multiple-entity-row'
    hide_state: true
  - type: section
  - entity: camera.aarlo_mobile
    name: Mobile camera
    primary:
      entity: sensor.aarlo_captured_today_mobile
      name: Captured today
    type: 'custom:multiple-entity-row'
    hide_state: true
show_header_toggle: false
title: Arlo
type: entities```

**Comment by Zegafur** [comment]
+1 Love the card, but this bug/feature is a bit annoying.

**Comment by benct** [comment]
Thanks for reporting the issue. However, I cannot seem to reproduce the problem in my test environment. Might be because I'm still a couple versions behind om HA and they have done some sort of change to the click handlers in the latest release. I will look into this asap.

Can any of you see any error messages in your browser console window (F12) when you try to click the element?

**Comment by fabricioavil** [comment]
btw, ignore my last comment about animation, I just saw that any click on this card doesnt show it being pressed in my phone.

**Comment by benct** [comment]
I'm pretty sure [these changes](https://github.com/home-assistant/home-assistant-polymer/pull/4023) are the reason why it is no longer working... I will have to add some custom click handling on the row element in my card now.

**Comment by benct** [comment]
Should be [solved](https://github.com/benct/lovelace-multiple-entity-row/commit/367090dd18f3340527c148ff06c8d7e4bead161e) in version 1.4.1 :)

**Comment by newlund** [comment]
Thank you! Working great! :)
