### ISSUE TITLE
Decimal separator localization 

### ISSUE THREAD

**Issue by gualandd** [benct/lovelace-multiple-entity-row#162]
Hi, I’m using multiple entity row in HA but I see that the decimal separator is not in locale form but in english form: I live in Italy and we use comma for decimals, not the dot.
Is possible to add the localization to have the right number separation?

**Comment by t-solak** [comment]
Agree, same issue for me in DE.
Would be very much appreciated if the hass locale format could be considered.

**Comment by kukulich** [comment]
https://github.com/home-assistant/frontend/pull/7925

**Comment by JonahKr** [comment]
this will come with the new version of custom-card-helpers *natively*
