### ISSUE TITLE
haptics support for tap_action

### ISSUE THREAD

**Issue by myhomeiot** [benct/lovelace-multiple-entity-row#164]
Please add [haptics](https://companion.home-assistant.io/docs/integrations/haptics/) support for tap_action, like it's already added in [button-card](https://github.com/custom-cards/button-card) and few other custom cards.
Thanks in advance.

**Comment by benct** [comment]
Added in version `4.2.0`

**Comment by myhomeiot** [comment]
> Added in version `4.2.0`

Thanks! Works great!

It's very useful, now interface looks very responsive! Is it possible make `haptic: selection` as a default for all tap actions? Or I should use styles some how?
