### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by aletzi1** [benct/lovelace-multiple-entity-row#166]
Hi,
Im new with lovelace multiple entity row and i need some help with it.
I made a picture what i mean. I want to put door sensor battery level to spots 1,2,3 and 4 (Underneath Suljettu/Closed)

Is it possible to put battery level underneath sensor data (open or closed) ?

<img width="857" alt="battery level possible" src="https://user-images.githubusercontent.com/66028464/105632585-a00ada00-5e5c-11eb-8d81-a4896bcd63a4.PNG">

> type: entities
> entities:
>   - entity: binary_sensor.0x158d000462b37e_contact
>     type: 'custom:multiple-entity-row'
>     name: Ovet
>     state_header: Tuulikaappi
>     entities:
>       - entity: binary_sensor.0x158d00046110ff_contact
>         name: Kylpyhuone
>       - entity: binary_sensor.0x158d000462b376_contact
>         name: Autotalli
>       - entity: binary_sensor.0x158d00045f9b5e_contact
>         name: Varasto

**Comment by benct** [comment]
No. You would have to add another multiple-entity-row underneath, but its not certain that it will align with the one above.
