### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by xinhu808** [benct/lovelace-multiple-entity-row#171]
since HA version 2020.2.0,  
![微信图片_20210212153219](https://user-images.githubusercontent.com/32804301/107741180-9d0e5580-6d47-11eb-86ac-3dbf92e4879d.png)
![微信图片_20210212153234](https://user-images.githubusercontent.com/32804301/107741183-9ed81900-6d47-11eb-8390-28fc2e2a2f41.png)

**Comment by sciorty** [comment]
I'm running Home Assistant 2021.2.3 and the entities that used to show on previous versions have now gone!

Before:
![photo5859587173303563633](https://user-images.githubusercontent.com/6460914/107967822-e6f87500-6fad-11eb-822e-a6de84fe5dd4.jpg)
After:
![photo5859587173303563632](https://user-images.githubusercontent.com/6460914/107967810-e233c100-6fad-11eb-9caf-745a2a47ada8.jpg)

Same code, but the entities under the 
`    type: 'custom:multiple-entity-row'`
 are not shown anymore

**Comment by benct** [comment]
No idea what the problems are in any of the above examples. Please create separate issues and provide more detailed information about the problem.
