### ISSUE TITLE
Support Msec to hours

### ISSUE THREAD

**Issue by poudenes** [benct/lovelace-multiple-entity-row#174]
Hi All,
Love this add-on so much!!! use it for many things!!

I have some sensors that show the uptime in msec. How can I change this to convert them to hours?
Or is there a way to make it possible to support this to convert it to hours?

Cheers,
Peter

**Comment by benct** [comment]
I'm guessing `format: duration` will not work, as your sensors are in milli(?)seconds? If so you could make a template sensor that divides your sensor value by 1000, and then use the duration formatting option. Not sure I want to add custom conversions for all types of numbers, but I'll see what can be done.

**Comment by mitch-thomas** [comment]
I would also appreciate this feature - in a  more general form: 
Add a configuration property "convert" to scale the value before displaying it.
This allows for the above conversion as well as converting from Wh to kWh (without using template senors).

**Comment by benct** [comment]
Added formatting option `duration-m` in version `4.4.0` for converting milliseconds to a HA duration.

(also added `kilo` to convert Wh to kWh, i.e. divide number by 1000)
