### ISSUE TITLE
Support for time formating without seconds

### ISSUE THREAD

**Issue by sstefanowski** [benct/lovelace-multiple-entity-row#183]
Hello,
Thanks for implementing this great extension. I find it very useful in my setup in many places. Thanks again.

Now, I wonder if you can do some simple but useful extension....
 I have some input_datetime fields to set the "thermostat schedules" (changing temperatures at certain hours).
The time settings allow are with minute granularity `HH:mm` while when injected to multiple entity row it always is rendered as `HH:mm:ss`

The screenshot below (sorry for mixed languages :))

![Thermostat Control](https://user-images.githubusercontent.com/36473471/112906811-1e019080-90ed-11eb-88f2-e95c1bbac020.jpg)

Could we have more flexible time (or also date) formatting?
Hmm.... I guess this change could be relatively easy to implement...

**Comment by benct** [comment]
Default formatting of input_datetime as `HH:mm` was just added in version `4.2.0` (see #140). Try upgrading and remove any `format` options.
