### ISSUE TITLE
"main entity" to work and display as the "header switch"?

### ISSUE THREAD

**Issue by igorsantos07** [benct/lovelace-multiple-entity-row#184]
Hello man! First of all, thanks for this component. The group is pure beauty :)
I guess, given the sheer amount of settings, it wouldn't be possible to make that into the Visual Editor, right? Would be awesome to have this in the main Hass distribution!

Anyways, here I go: I was wondering if it's somehow possible to make the main entity show the state of "any entity from the row" like the header switch does. I tried making the main entity something like "group.kitchen", to no avail. I guess it would be possible to make its tap_action to turn on or off the whole group, but it would still show no status, and I think there's no "toggle" action to use on a group?

Also, I understand the header switch only cares for the main entities, right? I see if I enable another entity from the row, it doesn't turn on together.

![image](https://user-images.githubusercontent.com/532299/113056007-9fa2fe00-9181-11eb-822c-c4a69336a4c2.png)

Best regards and thanks!

**Comment by benct** [comment]
Thanks for the kind words :)

It should be possible to support the visual editor, but it would be a big task to do so. Would indeed be great if HA would like to implement this into the main distribution!

The main entity is handled by HA's generic-entity-row component and I don't think I would be able to make it be "aware" of the other entities in the card and their state. So unfortunately I don't think this will be possible at the moment at least.

The header switch only handles the main entities of the rows, as this too is handled by HA's entities card and main row handlers, and have no direct connection with my card or the additional entities.
