### ISSUE TITLE
Does the 'style' field support templating?

### ISSUE THREAD

**Issue by brujoand** [benct/lovelace-multiple-entity-row#187]
It would be really nice to be able to change the color of an entity value based on some attribute. For instance I'm now displaying the current price of electricity, and I'd like to have the text be red when it's expencive. Is there currently a way to do that?

**Comment by benct** [comment]
Unfortunately not. There's an issue (#35) on supporting templating at some point.

The [card-mod](https://github.com/thomasloven/lovelace-card-mod) plugin should be able to handle this for now, though.
