### ISSUE TITLE
Borders too tight. 

### ISSUE THREAD

**Issue by calas80** [benct/lovelace-multiple-entity-row#190]
HI ^_^
I can't understand why these voices are so close to the edge. 

![immagine](https://user-images.githubusercontent.com/48358142/118476419-c2777a80-b70d-11eb-934c-a13f2b274df9.png)
![immagine](https://user-images.githubusercontent.com/48358142/118476693-21d58a80-b70e-11eb-908c-c8af581d107a.png)

 It's not like in your example. 

![immagine](https://user-images.githubusercontent.com/48358142/118476772-3d409580-b70e-11eb-92fa-486a74a214e1.png)

**Comment by TobiasSchwarz74** [comment]
the example shows the rows in an entities card.

**Comment by benct** [comment]
☝️ Wrap it in an entities card.
