### ISSUE TITLE
show cover action buttons

### ISSUE THREAD

**Issue by thecobra666** [benct/lovelace-multiple-entity-row#199]
I do not want the card to show the state of my covers (screens) because they don't have any. The state is always unkown. It does need to show me the buttons to move the cover up or down. How do I do that?

`type: entities
entities:
  - entity: cover.opslagkamer
    type: custom:multiple-entity-row
    entities:
      - entity: sensor.screen_sensor_opslagkamer
        name: false`

![image](https://user-images.githubusercontent.com/69201922/125189326-d506bf80-e237-11eb-9813-f3074128aa98.png)
![image](https://user-images.githubusercontent.com/69201922/125189331-da640a00-e237-11eb-8d96-85bfe2b13343.png)

**Comment by TobiasSchwarz74** [comment]
You can use tap_action call_service like this:

      - type: custom:multiple-entity-row
        entity: cover.eg_schlafzimmer_rolladen
        show_state: false
        state_color: false
        name: Rolladen
        tap_action: none
        entities:
          - entity: cover.eg_schlafzimmer_rolladen
            name: false
            icon: mdi:arrow-up-bold-outline
            tap_action:
              action: call-service
              service: cover.open_cover
              service_data:
                entity_id: cover.eg_schlafzimmer_rolladen
            styles:
              padding-right: 15px
          - entity: cover.eg_schlafzimmer_rolladen
            name: false
            icon: mdi:arrow-down-bold-outline
            tap_action:
              action: call-service
              service: cover.close_cover
              service_data:
                entity_id: cover.eg_schlafzimmer_rolladen
            styles:
              padding-right: 5px
          - entity: cover.eg_schlafzimmer_rolladen
            name: false
            icon: mdi:window-shutter
            tap_action:
              action: call-service
              service: cover.set_cover_position
              service_data:
                entity_id: cover.eg_schlafzimmer_rolladen
                position: 20
            styles:
              padding-right: 10px

**Comment by benct** [comment]
Cover entities are not directly supported (yet). As mentioned above, use a custom tap action with a service call.
