### ISSUE TITLE
Custom secondary info

### ISSUE THREAD

**Issue by hardtekpt** [benct/lovelace-multiple-entity-row#2]
Is there a way to modify this card to change the secondary info just like this: https://github.com/custom-cards/secondaryinfo-entity-row

**Comment by benct** [comment]
Not at the moment, but I might try to add that possibility in the future. Depending on how you want to display things, you might want to have a look at [attribute-entity-row](https://github.com/benct/lovelace-attribute-entity-row) too?

**Comment by hardtekpt** [comment]
I've managed a work around, I just put the name of the sensor in a section and used the name as a template to display what I wanted. This is what it looks like:


<img width="453" alt="Captura de ecrã 2019-07-19, às 01 16 05" src="https://user-images.githubusercontent.com/25752785/61500391-e4ddc700-a9c2-11e9-8a13-f05a49b9ee23.png">


Just took a look at the attribute-entity-row and it might be useful as well. Great components!

**Comment by benct** [comment]
Good workaround!

I will add support for using attributes/entities as secondary_info, but it will unfortunately not be as customizable as secondaryinfo-entity-row.
