### ISSUE TITLE
It doesn't work with HA Cast

### ISSUE THREAD

**Issue by mario-tux** [benct/lovelace-multiple-entity-row#20]
It looks that this custom component is not compatible with Home Assistant Cast. In my main page I configured some rows with this component: it work on Chrome on PC but I get an error message when casted on my Nest Hub Max: `Custom element doesn't exist: multiple-entity-row`.

screenshoot: https://imgur.com/a/6Apd8wp

The FAQ on the HA Cast website doesn't help: https://cast.home-assistant.io/faq.html

**Comment by benct** [comment]
Thanks for reporting this. I have not yet had a look at the HA Cast feature, but I wouldn't think the cards needed specific support for "casting". I will have to have a closer look at the documentation or dev forums when I get the time.

**Comment by Mariusthvdb** [comment]
+1 and thanks for looking in to it. Really appreciated if you could solve this.

We had an issue like this with the custom button-card and decluttering card, which has now been solved by the author Romrider. Maybe his solution is of interest for your card too?

**Comment by mario-tux** [comment]
> Thanks for reporting this. I have not yet had a look at the HA Cast feature, but I wouldn't think the cards needed specific support for "casting". I will have to have a closer look at the documentation or dev forums when I get the time.

My understanding is that you don't need a specific support/feature but, on opposite, you are using some specific element/feature that is not present in the more restricted casting environment.

Thank you for the support.

**Comment by benct** [comment]
Could you try the latest version of the card on HA Cast now and see if it works any better?

**Comment by benct** [comment]
Just tried out the casting functionality on my own system with the updated card, and it seems to be working as expected. Let me know if it still doesn't work for you.

**Comment by mario-tux** [comment]
I can confirm that this fixed the problem of casting on my Hub Max. Thanks.

**Comment by Mariusthvdb** [comment]
yep +1, thanks a lot!
