### ISSUE TITLE
core-2021.8.1

### ISSUE THREAD

**Issue by rEs-84** [benct/lovelace-multiple-entity-row#203]
Is this compatible with 2021.8.x?
Just installed via HACS, chrome f12 shows the js file loaded and accessible. 
Tried outside of HACS first.

Always get
Custom element doesn't exist: multiple-entity-row.

tried
type: entities
entities:
  - entity: binary_sensor.garageopener_firmware_update
    type: custom:multiple-entity-row
    name: One entity
    secondary_info: installed_version

Just installed custom:webos-keyboard-card, as spotted it while trying this. That works first time.
Updated HACs and rebooted whole machine
Hard cleared cache via F12 refresh

Initially just wondering if others with this custom card are running the latest / near latest version?

thanks in advance
Rob

**Comment by EnochPrime** [comment]
I am running 2021.8.7 and have not had an issues with this card.

**Comment by TobiasSchwarz74** [comment]
works for me too in 2021.8.8
try to reinstall using HACS
