### ISSUE TITLE
Support counter in row

### ISSUE THREAD

**Issue by SAOPP** [benct/lovelace-multiple-entity-row#206]
It would be great to be able to insert counters into a string, with dynamic interactive display of the count.

**Comment by benct** [comment]
Not quite sure what you mean. Does HA have a specific counter entity? Any examples would be helpful.

**Comment by SAOPP** [comment]
I somehow missed your answer, I meant that at the time of writing the question, if you specify a timer as an entity, then it was displayed in its default state, i.e. for example, if the timer is running, then it displays its default period, for example, 05:00, there was no dynamics, the timer did not visually show its countdown.

To be honest, I don't know if this is relevant or not for the current day, I didn't check it :) I just opened my question here... ;)
