### ISSUE TITLE
LitElement has already been declared

### ISSUE THREAD

**Issue by ch3funio** [benct/lovelace-multiple-entity-row#21]
hi, after last update (ca8030c), plugin stops working ;(
i got error in log:
`https://[myip]/community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js:1:1 Uncaught SyntaxError: Identifier 'LitElement' has already been declared`
any help appreciated

**Comment by benct** [comment]
Can you try updating again now and see if it works again?

**Comment by ch3funio** [comment]
i just did (8fa9573), no changes;(
`/community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js:1:1 Uncaught SyntaxError: Identifier 'LitElement' has already been declared` in log again
Chrome on Windows, cleard cashe. hassio after reboot

**Comment by benct** [comment]
What if you uninstall the plugin and then install it again?

**Comment by ch3funio** [comment]
meanwhile it worked, after refreshing the page it hung again. uninstall / install also did not help

**Comment by benct** [comment]
Try updating again now. I've added some changes that should fix the declaration error.

**Comment by ch3funio** [comment]
yep, its working, thanks!
