### ISSUE TITLE
 how to hide the last column ?

### ISSUE THREAD

**Issue by m4sis** [benct/lovelace-multiple-entity-row#210]
Hello,

I wish I could erase the surrounding information.
In order to keep data alignment and be harmonious.

How can I do?
![Capture d’écran 2021-10-29 172034](https://user-images.githubusercontent.com/75539603/139460854-2d0d8d6a-dc21-4685-9bb8-c6fab2541997.png)

**Comment by boybert** [comment]
I think specifying `show_state: false` at the root level of the row will do what you want.

**Comment by ildar170975** [comment]
> erase the surrounding information.

Not clear for me, what do you need?
Attach some pics with desired design.
