### ISSUE TITLE
Home Assistant Cast not working

### ISSUE THREAD

**Issue by DarkShortie** [benct/lovelace-multiple-entity-row#213]
Home Assistant Cast is not working, it shows "Custom element doesn't exist: multiple-entity-row".
Other custom cards are working.

According to the Home Assistant Cast [FAQ](https://cast.home-assistant.io/faq.html) this is an issue with the card.

> Some custom cards rely on things that are only available in the normal Home Assistant interface. This requires an update by the custom card developer.

> If you're a custom card developer: the most common mistake is that LitElement is extracted from an element that is not available on the page.

**Comment by NickM-27** [comment]
This is working for me with 2021.12

**Comment by benct** [comment]
Seems they have fixed some [cast issues](https://www.home-assistant.io/blog/2021/12/11/release-202112/#cast-issues-resolved) in 2021.12.
