### ISSUE TITLE
Broken  change ? 

### ISSUE THREAD

**Issue by AngelofromTurin** [benct/lovelace-multiple-entity-row#22]
Hi 
With the last update ( the first one of today)
I cant see the card in the lovelace... 
custom element doesn’t exist... 
something change in the configuration ? I dont see any change in the configuration

**Comment by benct** [comment]
The last update contains quite a few changes to the code, so yes, something might be broken on some systems/browsers. Try to update to the absolute latest version, clear your browser cache and see if that helps. If not, please post any errors from your browsers console window.

**Comment by AngelofromTurin** [comment]
Hi! thanks for your quick reply;  I tried with the app for iOS, with Chrome for iOS and with safari also but nothing.  at the moment I can't open the laptop.  would it be possible in hacs to put the previous version for a downgrade?  thank you very much

**Comment by benct** [comment]
Everything is working fine here, but only tested using Chrome and Safari on Mac and Chrome on Android. I'll wait with downgrading it until I can get more info on what is failing (on iOS?).

**Comment by AngelofromTurin** [comment]
well i tried to uninstall the plugin and install it again.  now it works well both in iOS app and in various browsers ... it was probably only my problem.
