### ISSUE TITLE
Tap action icon issue

### ISSUE THREAD

**Issue by 1iverea9er** [benct/lovelace-multiple-entity-row#224]
I have created lovelace panel:
![Снимок экрана 2021-12-30 112320](https://user-images.githubusercontent.com/82063500/147734424-83f5c338-9f9e-40d1-95fb-5ebd46ba4aab.png)
And I would like to configure this panel in the following way: when I click on the 'mdi:tune-vertical' icon, I can follow the external link to my router settings. For this, I use the following code below:

> 
                - entity: sensor.mikrotik_cpu_load
                  type: custom:multiple-entity-row
                  toggle: false
                  show_state: false
                  name: System
                  entities:
                    - entity: sensor.mikrotik_cpu_load
                      name: CPU Load
                    - entity: sensor.mikrotik_hdd_usage
                      name: HDD usage
                    - entity: sensor.mikrotik_memory_usage
                      name: Memory usage
                    - icon: 'mdi:tune-vertical'
                      tap_action:
                        action: url
                        url_path: http://192.168.1.1/

But at the same time the panel additionally open a link to router settings, the entity status window also appears. But I do not request it. It looks like, see screenshot:
![Снимок экрана 2021-12-30 113334](https://user-images.githubusercontent.com/82063500/147735062-591f65b7-b88e-4edb-85d3-5309062950f5.png)

I have tried to change the code several times in different ways:

first attempt

> 
                - entity: sensor.mikrotik_cpu_load
                  type: custom:multiple-entity-row
                  toggle: false
                  show_state: false
                  name: System
                  tap_action:
                        action: url
                        url_path: http://192.168.1.1/
                  entities:
                    - entity: sensor.mikrotik_cpu_load
                      name: CPU Load
                    - entity: sensor.mikrotik_hdd_usage
                      name: HDD usage
                    - entity: sensor.mikrotik_memory_usage
                      name: Memory usage
                    - icon: 'mdi:tune-vertical'

second attempt

> 
                - entity: sensor.mikrotik_cpu_load
                  type: custom:multiple-entity-row
                  toggle: false
                  show_state: false
                  name: System
                  tap_action:
                        action: url
                        url_path: http://192.168.1.1/
                  entities:
                    - entity: sensor.mikrotik_cpu_load
                      name: CPU Load
                    - entity: sensor.mikrotik_hdd_usage
                      name: HDD usage
                    - entity: sensor.mikrotik_memory_usage
                      name: Memory usage
                    - icon: 'mdi:tune-vertical'
                      tap_action:
                        action: url
                        url_path: http://192.168.1.1/

In the nutshell, I couldn't reach the correct operation of the panel.

**Comment by hmmbob** [comment]
Ah, I just came here with a similar issue. 

Q for you: does this happen on mobile (using HA app), or also on your PC? I noticed that on mobile stuff doesn't work as expected, but on PC it does.

**Comment by benct** [comment]
This should have been fixed in version `4.3.2` and HA >= `2021.12.4`

**Comment by hmmbob** [comment]
I'm on `4.4.1` and HA `2021.12.7`. How can I help troubleshoot?

like said: works fine on browser, but in the HA app the main entity `more-info` dialog pops up.

**Comment by 1iverea9er** [comment]
My HA version 2021.12.5 and lovelace card version 4.4.1.

Everything described concerns the web version.

On a mobile version link dont open, only  entity status window

**Comment by ildar170975** [comment]
> lovelace card version 4.4.1.

You better test with the latest version.

**Comment by hmmbob** [comment]
> > lovelace card version 4.4.1.
> 
> You better test with the latest version.

? 4.4.1 _is_ the [latest version](https://github.com/benct/lovelace-multiple-entity-row/releases/tag/v4.4.1) ....

**Comment by ildar170975** [comment]
Sorry, my mistake

**Comment by 1iverea9er** [comment]
I noticed that the problem exists only if I log into the home assistant interface via a laptop remotely using nabucasa. 

The problem disappears when I log via a desktop computer located on a local network (by ip address). 

And even if I connect to a local network on a laptop, the problem is also solved. 

Maybe this information will help to identify the cause.

**Comment by benct** [comment]
I have no idea what could cause this, as it should have been fixed in the latest versions. Guessing it is some caches that aren't being cleared..
