### ISSUE TITLE
NotSupportedError: CustomElementRegistry.define: 'multiple-entity-row' has already been defined as a custom element

### ISSUE THREAD

**Issue by alexsrb** [benct/lovelace-multiple-entity-row#228]
Hi,

I am observing the following error in the HA log:

Logger: frontend.js.latest.202112290
Source: components/system_log/__init__.py:189
First occurred: 10:57:18 (2 occurrences)
Last logged: 11:01:54

http://<FQDN redacted>:8123/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js:1:0 NotSupportedError: CustomElementRegistry.define: 'multiple-entity-row' has already been defined as a custom element

All components (HA Core/Supervisor/OS, HACS, etc.) are up-to-date:

## System Health

version | core-2021.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4928
Installed Version | 1.18.0
Stage | running
Available Repositories | 939
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 48.5 GB
disk_used | 17.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.9.0), File editor (5.3.3), Mosquitto broker (6.0.1), Samba share (9.5.1), Grafana (6.3.3), Log Viewer (0.12.1), SSH & Web Terminal (10.0.0), Studio Code Server (3.7.0), InfluxDB (4.0.6)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 5
views | 5
mode | storage

</details>

**Comment by ildar170975** [comment]
How was the card installed?
Was it by HACS?
Did you register the card manually? (have you added this card as a resource manually?)

**Comment by alexsrb** [comment]
> How was the card installed? Was it by HACS? Did you register the card manually? (have you added this card as a resource manually?)

Via UI/HACS. No actions carried out manually / via any .yaml file.

**Comment by benct** [comment]
Is this still an issue? I have no idea what could cause this. Try clearing your browser cache etc..? If still a problem, maybe create an issue in the HA frontend repo..
