### ISSUE TITLE
Readme Clarification

### ISSUE THREAD

**Issue by turtleprince** [benct/lovelace-multiple-entity-row#231]
This does not exist in current HA:

> The above configuration can be managed directly in the Configuration -> Lovelace Dashboards -> Resources panel when not using YAML mode,

After clicking Configuration, there is no entry "Lovelace Dashboards". If you click "Dashboards", there is no "Resources" panel either.

> or added by clicking the "Add to lovelace" button on the HACS dashboard after installing the plugin.

There is no "Add to lovelace" button anywhere on HACS that I can find.

**Comment by benct** [comment]
Thanks, will update the readme shortly.
