### ISSUE TITLE
Allow not specifying the entity for Entity objects.

### ISSUE THREAD

**Issue by i00** [benct/lovelace-multiple-entity-row#24]
I often automate the filling of entries with auto-entities... but I still have to use attribute-entity-row in some instances (when automating the filling of entities) because it actually doesn't require specifying an entity name ... can you make the entity and attribute fields conditional so that at least one must be specified.
If attribute is entered with no entity, then the primary entity will be used.

**Comment by benct** [comment]
Already working on it (see #23) :)
