### ISSUE TITLE
<center>

### ISSUE THREAD

**Issue by rhgiter** [benct/lovelace-multiple-entity-row#244]
is it possible to remove ikon and center the text ? 
![image](https://user-images.githubusercontent.com/61065752/160166181-ce57b94f-59ae-40a0-bad1-0669552b8172.png)

**Comment by ildar170975** [comment]
1. Next time please use a more clear title for the issue. It is possible to use more than 8 chars in the title (a "space" char is supported too).
2. Possible with card-mod: go to Community thread for card-mod ->1st post -> link at the bottom -> styles for multiple-entity-row.

**Comment by ildar170975** [comment]
https://community.home-assistant.io/t/lovelace-multiple-entity-row/109109/198
https://community-assets.home-assistant.io/original/4X/d/0/5/d05f8e9c8156a88b9a1fa1ad943a5e8e1ec5ac88.png

@[rhgiter](https://github.com/rhgiter)
Is the provided solution suitable for you?
If yes - please close the issue.

**Comment by rhgiter** [comment]
Thanks.  I look like to Will Work
