### ISSUE TITLE
Wrong installation patch

### ISSUE THREAD

**Issue by JanosAudron** [benct/lovelace-multiple-entity-row#26]
I'm at the beginning of using Home Assistant, so maybe it's my fault, but I might found a bug. I installed the plugin with HACS, and by default the component is in "/config/www/community/lovelace-multiple-entity-row", but I had the error below. Moving the files into "/config/www" error goes away
![image](https://user-images.githubusercontent.com/1606318/72204074-511e1c80-3474-11ea-9c86-605c5f8280b7.png)

**Comment by benct** [comment]
Hm, that's strange.. When/if you get that error again, check if there are any errors in the browser console window which often includes more info on what's wrong.

Not sure you have added the following, but if you install using HACS, I think you can skip this configuration all together.
```
- url: /local/multiple-entity-row.js?v=2.2.0
  type: module
```

**Comment by benct** [comment]
I've updated the readme to include proper paths for HACS.
