### ISSUE TITLE
Add State as valid Secondary_Info option

### ISSUE THREAD

**Issue by lazyboy0172** [benct/lovelace-multiple-entity-row#273]
Right now we can bring in entity attributes as secondary_info on the card, but I'd really like to bring in the actual state of the entity.

When showing multiple entities, having the state of the 'main' entity as its own tile ends up taking a lot of room. This could take up no extra space by utilizing the same area that secondary_info would be.

Here's an example of what I have now, what it looks like without secondary_info, and how I'd like the end result to look:
![image](https://user-images.githubusercontent.com/57650025/199734842-d4ffd07a-ae69-4d3f-bb48-52fbe114ef87.png)
currently I have a multiple-entity-row for my ember mug, displaying the battery, amount of liquid, and temps of the mug. The main entity is the mug itself, which tells me if it's cooling, heating, or at the perfect temperature.

If I allow the card to show_state of the main entity, it pushes everything and doesn't really fit:
![image](https://user-images.githubusercontent.com/57650025/199735172-15d6ee09-8b99-48d3-9916-4723a2ea813e.png)
I could remove units and probably be okay here, but it's not my ideal scenario.

Here's what I'd prefer: 
![image](https://user-images.githubusercontent.com/57650025/199735335-f9a08dda-a38d-4033-8517-f395b2742f29.png)
in this case I obviously just hard-coded the 'Perfect' text as the secondary_info, but it shows that it does fit well. And with multiple-entity-row already being able to pull in entity attributes to that location, I'd love to be able to pull the actual state itself there as an additional option.

**Comment by ildar170975** [comment]
There is some inconsistency here.
Check docs again:
![изображение](https://user-images.githubusercontent.com/71872483/200154126-fcbaf80e-bf52-4a89-a1b1-0105ed67235e.png)

First let's check documented cases:
-- display some text
-- display an attribute

![изображение](https://user-images.githubusercontent.com/71872483/200154178-b208f1c0-8c66-4bc6-8a0b-8912c3219b98.png)

Regarding showing a state - it is not documented.
But this anyway possible:
![изображение](https://user-images.githubusercontent.com/71872483/200154422-53f88df5-f617-495d-86de-489a7309593c.png)


An then note this remark - "or skip to use main entity".
It does NOT work:
![изображение](https://user-images.githubusercontent.com/71872483/200154404-5c4b5f8b-2e3b-451b-a542-141f04b447d5.png)

But also there is a weird workaround - using an `icon` option:
![изображение](https://user-images.githubusercontent.com/71872483/200154369-9f1ed59e-9b0d-4403-b23d-e30d9273f268.png)

**Comment by lazyboy0172** [comment]
ah, clever, thank you. Hadn't thought of assigning the same entity as the secondary info to get its state there.
