### ISSUE TITLE
tap_action is more-info

### ISSUE THREAD

**Issue by 1iverea9er** [benct/lovelace-multiple-entity-row#275]
more-info entity does not show when tap_action is more-info for the main entity. Instead, it shows the main entity

>                       
                       - entity: sensor.lr_trv_position
                          type: custom:multiple-entity-row
                          toggle: false
                          show_state: false
                          state_color: false
                          name: Valve (Livingroom)
                          tap_action:                                                  _this work incorrect_
                            action: more-info
                            entity: sensor.lr_trv_calibration
                          secondary_info: 
                            entity: sensor.lr_trv_calibration
                            name: Calibration
                          entities:
                            - entity: sensor.lr_trv_position
                              name: false
                              tap_action:                                                  _this work correct_
                                action: more-info
                                entity: sensor.ra_lr_position

**Comment by ildar170975** [comment]
Overriding entity for more-info for the MAIN entity is not working now.
https://github.com/benct/lovelace-multiple-entity-row/issues/188#issuecomment-996801877
Duplicate of https://github.com/benct/lovelace-multiple-entity-row/issues/188

**Comment by ildar170975** [comment]
This functionality was added in HA 2024.11.
The issue can be closed.

**Comment by 1iverea9er** [comment]
Yes, now it's solved
