### ISSUE TITLE
Main entity as icon with name

### ISSUE THREAD

**Issue by SAOPP** [benct/lovelace-multiple-entity-row#279]
Hi!

It possible to make `icon: true` in main entity of row?

Here is example:

![image](https://user-images.githubusercontent.com/5647009/210009606-33106b61-3fc7-4697-a17e-4632fd987cee.png)

The main's entity option like `icon: true` is not working for it. I got out of the situation by adding a voltage sensor as the main entity, but still I wonder if it is not possible now, can this be implemented in the future?

Here is my current "solved" issue :laughing: 
![image](https://user-images.githubusercontent.com/5647009/210009614-fbaaa159-150c-4c9b-aa3c-9a1521b60e64.png)

**Comment by rtasarz** [comment]
You can simply set `show_state: false` and then repeat the main entity as the last one in entities list. You may also consider disabling tap/hold actions of the main entity if you choose one that is only roughly related to entities from the list, this way it will effectively work as a row name only.
