### ISSUE TITLE
Q: When is an entity active?

### ISSUE THREAD

**Issue by sciurius** [benct/lovelace-multiple-entity-row#285]
From the docs:

> state_color | bool | false | Enable colored icon when entity is active

When is an entity active?

**Comment by ildar170975** [comment]
It is related to binary entities only:
binary_sensor
switch
input_boolean
sun

**Comment by sciurius** [comment]
Understandable. However, I use it for a binary sensor (sun.sun) but the icon still doesn't change colour.

````
  - type: custom:template-entity-row
    entity: sun.sun
    state_color: true
    condition: '{{ is_state(''sun.sun'',''above_horizon'') }}'
    name: Daglicht
    state: |-
      {{ as_timestamp(states.sun.sun.attributes.next_rising)
         | float | timestamp_custom('%H:%M')}}
      —
      {{ as_timestamp(states.sun.sun.attributes.next_setting)
         | float | timestamp_custom('%H:%M')}}
````

The dashboard does not show a coloured icon, when I click on it the info dialog does show a coloured icon.

![scrot20230204100648](https://user-images.githubusercontent.com/1118804/216759023-39d43306-92a4-49fe-bca1-6143256f82e0.png)

**Comment by ildar170975** [comment]
The code is not related to the multiple-entity-row.

**Comment by sciurius** [comment]
Oops... Sorry... Bad cut/paste.

**Comment by ildar170975** [comment]
Please close the issue if it is solved!))

**Comment by sciurius** [comment]
I've been struggling with the icon colours in custom:template-entity-row and I thought I had similar problems in custom:multiple-entity-row, hence the confusion.
AFAICS, multiple-entity-row behaves correctly.

Thanks for your patience and apologies for the noise.
