### ISSUE TITLE
Feature Request: Add "toggle all entities" functionality

### ISSUE THREAD

**Issue by Nikolay-Ch** [benct/lovelace-multiple-entity-row#287]
It is the useful to add functionality to toggle all entities in entities list.

I use Entities object that contains multiple EntityRow objects inside. And, at header of Entities object I see toggle button. And I use this button to turn on and off all lights in my home. But now EntityRow toggle only one "core" entity, and ignore all entities, that it contains in its entities list.

**Comment by benct** [comment]
I've looked into this some time ago, but I could not find a way to listen to the header toggle event to achieve this. So unfortunately, I'm not able to implement this.
