### ISSUE TITLE
is this repo abandoned?

### ISSUE THREAD

**Issue by jumping2000** [benct/lovelace-multiple-entity-row#291]
This repo has no commits since december 2021, and all issues raised and all PRs submitted are ignored.
@benct , do you still maintain this great card?

**Comment by benct** [comment]
I've unfortunately not had the time lately to keep up with these projects. I cannot promise anything, but I'll try to set aside some time soon™️ to at least implement PRs and/or fix bugs.

**Comment by jumping2000** [comment]
> I've unfortunately not had the time lately to keep up with these projects. I cannot promise anything, but I'll try to set aside some time soon™️ to at least implement PRs and/or fix bugs.

thank you
