### ISSUE TITLE
Multiple entity row entity state not working

### ISSUE THREAD

**Issue by PeterGillham** [benct/lovelace-multiple-entity-row#295]
I think this may be related to another issue but...
type: entities
entities:
  - entity: binary_sensor.ov70_xtz_doors_locked
    type: custom:multiple-entity-row
    name: Doors
    secondary_info: last-changed
    show_state: false
    entities:
      - entity: binary_sensor.ov70_xtz_door_closed_left_back
        name: N/S rear
      - entity: binary_sensor.ov70_xtz_door_closed_left_front
        name: N/S front
      - entity: binary_sensor.ov70_xtz_door_closed_right_back
        name: O/S rear
      - entity: binary_sensor.ov70_xtz_door_closed_right_front
        name: O/S front
      - entity: binary_sensor.ov70_xtz_doors_locked
        name: Secure
show_header_toggle: false
theme: Mushroom
Shows 
![image](https://user-images.githubusercontent.com/3073049/233005058-2cca2d71-3552-4706-8e62-736bbab8637e.png)
Whereas the entity 
type: entity
entity: binary_sensor.ov70_xtz_door_closed_right_back
shows
![image](https://user-images.githubusercontent.com/3073049/233005391-69d7f779-699b-4976-8551-93f0f70115ce.png)

The Multiple entity row used to show the correct state (open/closed) but has changed since the resent core updates

**Comment by ildar170975** [comment]
Duplicate https://github.com/benct/lovelace-multiple-entity-row/issues/292
