### ISSUE TITLE
Hide_if not working

### ISSUE THREAD

**Issue by EvertJob** [benct/lovelace-multiple-entity-row#297]
Hi,

I'm having a `binary_sensor` with a `off` value. I would like to hide the row if the state is `off` therefore want to use this:
```
  - entity: binary_sensor.meteoalarm
    type: custom:multiple-entity-row
    hide_if: 'off'
```

The row is not hiding for any reason. Good chance I'm doing something wrong but cannot figure out what.

**Comment by ildar170975** [comment]
> The row is not hiding for any reason.

The `hide_if` option as an property for an entity or a secondary_info, not for the whole row.
https://github.com/benct/lovelace-multiple-entity-row#entity-objects
https://github.com/benct/lovelace-multiple-entity-row#secondary-info
