### ISSUE TITLE
template with each entitie on a line

### ISSUE THREAD

**Issue by Fougues** [benct/lovelace-multiple-entity-row#298]
hello

On a line, the color of each entity can be chosen.
but when you add a condition, it doesn't work.
the color of the whole line must be changed.

type: entities
entities:
  - entity: input_number.point_rosee_salon
    type: custom:multiple-entity-row
    name: Salon
    icon: mdi:thermometer-water
    format: precision1
    state_header: Ro °C
    unit: false
    styles:
      font-weight: bold
      font-size: 17px
      background: yellow
      color: red
    entities:
      - entity: sensor.temperature_lumi_158d0004888b14
        name: T °C
        format: precision1
        unit: false
        styles:
          color: red
      - entity: sensor.humidity_lumi_158d0004888b14
        name: HR %
        unit: false
        format: precision1
        styles:
          color: |
            :host {
             {% if is_state(sensor.humidity_lumi_158d0004888b14) > 50  %}
                 red
             {% endif %}
             }

that does not work

**Comment by ildar170975** [comment]
You are trying to change a color by card-mod which is a different plugin - and yet creating an issue for multiple-entity-row.
