### ISSUE TITLE
Dynamic coloring

### ISSUE THREAD

**Issue by cm2962** [benct/lovelace-multiple-entity-row#312]
Hi, 
I am a big fan of this enhancement.

However, I am wondering if it would be useful to have dynamic colored values as feature, too.

Eg. Temperature <10 = font color A; >=10 font color BB;....

Thx
Christian

**Comment by ildar170975** [comment]
Can use card-mod for this.
You are asking about a values' text color, but there are more possible customizations like icon color, headers' color etc.

**Comment by cm2962** [comment]
Ok thanks, I'll have a look into this. Was not aware of the fact that it works with this feature, as well.
