### ISSUE TITLE
Make the text and icons color customizable and/or adhere to the theme?

### ISSUE THREAD

**Issue by x99percent** [benct/lovelace-multiple-entity-row#34]
The white state text and icons for the service call setup stand out against everything else with my current theme. If there were any way to customize the text and icon color, or if they went with the current theme colors, that would be great!

**Comment by benct** [comment]
The icon is just a `<ha-icon>` element controlled/rendered by HA and the text has the `color: var(--secondary-text-color)` style, so by default it should follow your theme settings..? Seems to be working in my setup at least.

**Comment by x99percent** [comment]
Using the browser's inspect tool, as well as verifying with a WILD color change, the service call icons seem to be using `--primary-text-color`

**Comment by benct** [comment]
Then that is the default rendering of HA for icons, it is not something explicitly set by this card. In my system it seems like all the icons have the `var(--iron-icon-fill-color, currentcolor)` style, so maybe you could try setting that in your theme variables?
