### ISSUE TITLE
Tap Action Temperature Float Error

### ISSUE THREAD

**Issue by michaelcox12** [benct/lovelace-multiple-entity-row#348]
I want to have a plus and minus button to raise/lower temperature, but I can't get past a float error when using the code below

      - icon: mdi:plus
        tap_action:
          action: call-service
          service: climate.set_temperature
          service_data:
            entity_id: climate.downstairs
            temperature: {{ state_attr('climate.downstairs', 'temperature') | float + 1 }}

If I just do temperature: 78 it will change the setpoint, but otherwise I keep getting an error. I even tried a helper sensor but doing temperature: sensor.downstairs_raise_temp also got an error

Not sure if this a problem with multiple-entity-row or I'm just missing something

**Comment by ildar170975** [comment]
> temperature: {{ state_attr('climate.downstairs', 'temperature') | float + 1 }}

The card does not support jinja templates.
Not a bug, just a wrong use. Suggest to ask in Community first before creating an issue.

**Comment by michaelcox12** [comment]
Thanks, yeah, user error here, closing

**Comment by ildar170975** [comment]
Also, even if the card did support templates, the code should be like
```
temperature: >-
  {{ state_attr('climate.downstairs', 'temperature') | float + 1 }}
```
since the template is a string.
Just FYI.

**Comment by michaelcox12** [comment]
Thanks, I ended up making scripts for the plus/minus temp option and then calling the scripts as service, worked great, but took me way too long to get there lol
