### ISSUE TITLE
Restore the color of the active entity (state_color: true)

### ISSUE THREAD

**Issue by majdzik84** [benct/lovelace-multiple-entity-row#36]
In HA version 0.105 the icon color of enabled entities is turned off by default. You can enable them using state_color: true, but unfortunately it doesn't work on your card :( 
Would you be able to restore it?

![image](https://user-images.githubusercontent.com/31352476/73961507-037abf80-490d-11ea-975a-a61a40527097.png)

**Comment by Fulch** [comment]
I am also finding the same issue, would be great if this could be resolved.

**Comment by sajikur** [comment]
same here. Pleeeeease solve ;)

**Comment by benct** [comment]
Working on it.

**Comment by majdzik84** [comment]
Unfortunately, it doesn't work for me :( Have I set up correctly?
![image](https://user-images.githubusercontent.com/31352476/74040206-878f7e80-49c3-11ea-8f4c-e9f61e350d28.png)

**Comment by balaus68** [comment]
Hi, no changes with this update. Icons remain in the same state. Could you check code? Thanx

**Comment by Fulch** [comment]
Not working for me either unfortunately.

**Comment by benct** [comment]
I haven't had the chance to upgrade my system to v0.105 yet, so it's kinda difficult to test.

Can anyone with access to their HA file system edit the file `<config_folder>/www/community/lovelace-multiple-entity-row/multiple-entity-row.js` (if using HACS) or `<config_folder>/www/multiple-entity-row.js` (if installed manually) and try changing line 78 from `.stateColor="${this._config.state_color}"` to `.stateColor=${this._config.state_color}` and see if that helps?

**Comment by Fulch** [comment]
My apologies!

When I went to edit this file I realised that the line was not present, big clue that the browser cache had not been cleared and I was still looking at the old file.
Cleared cache, line is now present and all is working for me with no file edit necessary.

Thank you very much for the prompt fix.

**Comment by balaus68** [comment]
NEED to uninstall and reinstall (and refresh) MER to see the update. Now (seem) works for me. Thanks to supernerd mgiako for help!
