### ISSUE TITLE
JS errors if entity is not available

### ISSUE THREAD

**Issue by jacekpaszkowski** [benct/lovelace-multiple-entity-row#39]
```
Uncaught (in promise) Error: Entity not available: sensor.slave1_aqi_eco_marywilska_pm25
    at HTMLElement.set hass [as hass] (multiple-entity-row.js:136)
    at HTMLElement.value (hui-entities-card.ts:219)
    at HTMLElement.e.renderEntity (card-mod.js:1)
    at hui-entities-card.ts:144
    at Array.map (<anonymous>)
    at HTMLElement.value (hui-entities-card.ts:143)
    at HTMLElement.update (lit-element.ts:217)
    at HTMLElement.performUpdate (updating-element.ts:704)
    at HTMLElement._enqueueUpdate (updating-element.ts:653)
```

'sensor.slave1_aqi_eco_marywilska_pm25' is defined as primary entity

**Comment by benct** [comment]
It should really be saying entity does not exist, because the card cannot find that entity in the HA states registry. This has not changed since v2.3.0 though.. Are you sure you have the correct sensor and correct spelling?

**Comment by jacekpaszkowski** [comment]
In my case this is entity which is created in runtime. I noticed this issue now.

It is simple to reproduce. If i provide existing entity name (fan.salon_air_purifier) it works:
![image](https://user-images.githubusercontent.com/4264991/74586687-642f8980-4fea-11ea-9ca0-04e4b6fc1da8.png)
![image](https://user-images.githubusercontent.com/4264991/74586690-727da580-4fea-11ea-862f-3dacac3d11f6.png)

If i provide entity name which doesn't exist (fan.salon_air_purifier_2) it breaks:
![image](https://user-images.githubusercontent.com/4264991/74586701-92ad6480-4fea-11ea-8217-ebb5daede9b6.png)
![image](https://user-images.githubusercontent.com/4264991/74586705-ac4eac00-4fea-11ea-8260-ae35d0f7aad8.png)

![image](https://user-images.githubusercontent.com/4264991/74586707-af499c80-4fea-11ea-8dc0-cd1d5d6b194a.png)

**Comment by benct** [comment]
Well, that is the intended behaviour as an entity that doesn't exist has no data to display, breaking the card/plugin all together. So I don't know what you want me to do here?
