### ISSUE TITLE
State changes not being displayed until refresh

### ISSUE THREAD

**Issue by aheath70** [benct/lovelace-multiple-entity-row#4]
Not sure why, but when the state of an entity changes (e.g. from off to on), the state change is not reflected until a refresh of the web page is done (using F5 or the browser refresh button).

Hassio, running on a Raspberry Pi Model 3B+, 0.96.5.

**Comment by Alfiegerner** [comment]
Just to add to this, the primary and secondary values are updating fine, but the base entity state is not changing, F5 required to see new state.

**Comment by schwarzenbergf** [comment]
Same here. 
Moreover, using the toggle to switch to On or Off it falls back after a second to the previous state, not reflecting the current state until a browser refresh.

**Comment by P2mb2** [comment]
Same here !!! :(

**Comment by benct** [comment]
Sorry for the late reply, I'm currently abroad on vacation with limited internet. I will try to fix this issue as soon as I get back home.

**Comment by benct** [comment]
Version 1.2.2 should solve the issue. Let me know if it for some reason doesn't.

**Comment by schwarzenbergf** [comment]
It works, thank you!
