### ISSUE TITLE
Further simplify config

### ISSUE THREAD

**Issue by martijnve** [benct/lovelace-multiple-entity-row#40]
Now that the primary, secondary and tertiary entities have been simplified into just a list of entities I was thinking it should be possible to also include the main "entity" into that same list.

Is there a special reason it needs to be separated from the rest?

so from:
  - type: 'custom:multiple-entity-row'
    name: Gas use
    entity: sensor.hourly_gas_consumption
    state_header: Current
    entities:
      - entity: sensor.daily_gas
        name: Daily
      - entity: sensor.monthly_gas
        name: Monthly
    
to:
  - type: 'custom:multiple-entity-row'
    name: Gas use
    entities:
      - entity: sensor.daily_gas
        name: Daily
      - entity: sensor.monthly_gas
        name: Monthly
      - entity: sensor.hourly_gas_consumption
         name: Current
    type: 'custom:multiple-entity-row'

**Comment by benct** [comment]
I see why you could think that simplifies things, but it actually makes it somewhat more complicated to handle in the code, as well as being confusing which of the entities in the list is the "main" one.

However, the main reason for keeping this entity configuration, is to better match the configuration of all other entity row cards, in addition to the default Lovelace cards that are often configured in this way.
