### ISSUE TITLE
Add name above icon

### ISSUE THREAD

**Issue by majdzik84** [benct/lovelace-multiple-entity-row#41]
Is it possible to add a name above the icon?

![Adnotacja 2020-02-14 234957](https://user-images.githubusercontent.com/31352476/74574873-572c7f00-4f85-11ea-8f6f-c62f2736d6fe.png)

Thank you for the plugin, it's wonderful

**Comment by benct** [comment]
I didn't think icons needed much explanation, but I guess I can implement support for a name on icons too.

**Comment by majdzik84** [comment]
For example, I have a room in which I have several windows. I would like to know which one is open and the icons have the same :) THX
