### ISSUE TITLE
format time

### ISSUE THREAD

**Issue by yabuts** [benct/lovelace-multiple-entity-row#43]
hi i am trying to use this with multiple UTc timestamps with format time, that works OK with the regular entities card but on this card it does not work

 - entity: sensor.jewish_calendar_upcoming_havdalah
    format: time

**Comment by benct** [comment]
This is currently not supported. I could try to add support for it in the future.

**Comment by yabuts** [comment]
Thanks,  if you can make it work with template row like this https://github.com/thomasloven/lovelace-template-entity-row, then its options whould be endless
