### ISSUE TITLE
Haptic Feedback

### ISSUE THREAD

**Issue by jeremywillans** [benct/lovelace-multiple-entity-row#44]
Awesome Card! Love the update for extra entity support - great amount of flexibility!

Would it be possible to add haptic support for call-service ?
It works for the standard entity toggle, but not if using call-service.

**Comment by benct** [comment]
I tried to add haptic feedback for the 3.0 release, but I didn't get it to work for some reason.. I guess I'll have another go at it in the near future.

**Comment by jeremywillans** [comment]
@benct,

Thanks for adding this! However since upgrading, this card no longer loads on iOS
"Custom element doesn't exist: multiple-entity-row"

Works from from Chrome on Windows PC
