### ISSUE TITLE
Feature request: add hold_action

### ISSUE THREAD

**Issue by smhgit** [benct/lovelace-multiple-entity-row#50]
Support hold action

**Comment by benct** [comment]
Looked at adding hold action to the latest release, but this is seemingly much more difficult/complex than I thought. Will have to look further at how to implement this some other time.

**Comment by myhomeiot** [comment]
Please add double_tap_action as well.

**Comment by benct** [comment]
Both `hold_action` and `double_tap_action` supported on entity row in version `4.0.0`. They are however not yet supported on additional entities and on the state value itself, as these are handled differently and requires a lot more work to support.
