### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by randyarrasmith** [benct/lovelace-multiple-entity-row#54]
just updated to version 3.1.0 and it appears broken :)  

I have updated HA, and also tried in safari browser and iOS app.

web inspector: Unhandled Promise Rejection http:/xxxxxxx/community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js

BTW, just started using this week and like it.  Funny thing is the couple things I hoped it would do but didn't are already new in 3.1.0.  It is like you were reading my mind... LOL.  Thanks for making this. 

Now if we can get it to work again....  ;)

**Comment by Knapoc** [comment]
I have the same issue. Inspection with firefox:
`SyntaxError: expected expression, got '.' multiple-entity-row.js:286:67`

The code in question (last line):
```JavaScript
                if (config.action === 'url') {
                    return () => {
                        if (!confirmation || confirm(confirmation))
                            window.open(config.url_path, '_blank')?.focus();
```
