### ISSUE TITLE
element not found

### ISSUE THREAD

**Issue by poudenes** [benct/lovelace-multiple-entity-row#56]
After latest update to v3.1.0 I get this error on Safari (13.0.5) on macOS (10.13.6), HA: 0.106.4
Did a cache clear, no result

When I open HA in Chrome its working correct...

**Comment by sajikur** [comment]
> 
> 
> After latest update to v3.1.0 I get this error on Safari (13.0.5) on macOS (10.13.6), HA: 0.106.4
> Did a cache clear, no result
> 
> When I open HA in Chrome its working correct...

Same error here. Chrome works correctly, firefox "Custom element doesn't exist: multiple-entity-row."

**Comment by poudenes** [comment]
After reverting back to 3.0.0 everything working again

**Comment by mgiako** [comment]
On iOS (iphone and ipad) even chrome does not work, same error.
