### ISSUE TITLE
[Q] Is it possible to use an attribute as the name?

### ISSUE THREAD

**Issue by wsw70** [benct/lovelace-multiple-entity-row#63]
I noticed a lot of possibilities to display attributes almost anywhere except for the name.

I guess I could have  `name: false` and use `secondary_info` to provide a name coming from an attribute but there may be a simpler way?

**Comment by benct** [comment]
Sorry, this is not supported at the moment. Might be possible in a future version if I get templating implemented.

**Comment by wsw70** [comment]
Thanks you for the feedback.

I thought that since attributes are used pretty much everywhere I was missing the information to use them in `name`.  Now it is clear. Thanks.
