### ISSUE TITLE
Tap action url opens new window (bug?)

### ISSUE THREAD

**Issue by smhgit** [benct/lovelace-multiple-entity-row#66]
Action url opens new tab window. I was expecting it to be the same as navigation path (https://www.home-assistant.io/lovelace/actions/#tap-action).

If url action purpose is different, can you please add support for navigate?

**Comment by woodmj74** [comment]
+1, my experience (outside of this card) is that navigation path is in the same tab but URL opens a new tab. I'd love to see navigation support added here.

(other than awesome card which has improved my dashboard 100% - thanks!)
