### ISSUE TITLE
Lovelace-multi-row freeze Hassio dashboard editor

### ISSUE THREAD

**Issue by konceptnet** [benct/lovelace-multiple-entity-row#69]
It's my first review, I willd o my best to describe the problem.

When I try to edit the vertical block where I install the multi-row plugin it keep freezing my chrome tab. I nee to open the full file editor.

I attach my code to my comment
[basement.log](https://github.com/benct/lovelace-multiple-entity-row/files/4525189/basement.log)

**Comment by benct** [comment]
Not sure what can cause that.. could you try upgrading to v3.2.0? It might be a bug with the new `device_class` handling of `binary_sensor`s.

If that doesn't work, check if there are any error messages in the browser console window (press F12 and look at `console` in the devtools section)
