### ISSUE TITLE
Can't remove unit

### ISSUE THREAD

**Issue by TheLastProject** [benct/lovelace-multiple-entity-row#7]
![image](https://user-images.githubusercontent.com/1885159/64196394-0f58e600-ce84-11e9-979c-349f8e484818.png)

Not sure if I'm doing something wrong? This should work, right?

**Comment by benct** [comment]
Yes, it should. However, I see now that I might have accidentally removed that false check. I'll try to get this fixed as soon as possible. Thanks for pointing it out :)
