### ISSUE TITLE
add multiple-entity-row to entity card = errors

### ISSUE THREAD

**Issue by bertybassett** [benct/lovelace-multiple-entity-row#70]
If I create a new entity card and add this 

![Screenshot 2020-04-27 at 11 36 16](https://user-images.githubusercontent.com/5606175/80362901-55cbdc80-887b-11ea-9393-854b1aa4eaf5.png)

Despite the error it displays fine in Safari, Chrome, Firefox but not edge?

Resource URL has been added to HA dashboard in the new place.

![image001](https://user-images.githubusercontent.com/5606175/80370504-2e2f4100-8888-11ea-9d8b-a9053ee403db.jpg)

![Screenshot 2020-04-27 at 13 09 06](https://user-images.githubusercontent.com/5606175/80370580-53bc4a80-8888-11ea-818c-4a7409049271.png)

**Comment by benct** [comment]
Strange... can you see if there are any errors in the console output in Edge? (press F12, click `console` in the DevTools window)

**Comment by dodekaphilist** [comment]
That's what comes up for me
Maybe some hard-coded string, because a light with that name doesn't exist in my setup

![image](https://user-images.githubusercontent.com/31287077/88317515-abe4da80-cd19-11ea-85c8-bfdf3d500047.png)
