### ISSUE TITLE
device_class icon don't show up

### ISSUE THREAD

**Issue by dyfcom** [benct/lovelace-multiple-entity-row#72]
The icon from device_class (Battery, Window, etc.) don't show up, only the state. 

The entity is marked with `icon: true`.

```
          - entity: binary_sensor.0x00158d000394300f_contact
            name: Badezimmer
            icon: true
            state_color: true
```
![grafik](https://user-images.githubusercontent.com/47184285/80624387-e6591700-8a4b-11ea-8e63-b80ee76f6e33.png)

1) is a window-reedcontact as binary_sensor
2) are batterys as a normal sensor

**Comment by benct** [comment]
Should be fixed by #71
