### ISSUE TITLE
Define layout of a set of enities

### ISSUE THREAD

**Issue by StijnVdd** [benct/lovelace-multiple-entity-row#75]
Hi,

Basically it would be great to have a combination of [auto-entities](https://github.com/thomasloven/lovelace-auto-entitiesl) together with multiple-entity-row.

I have a fair amount of devices that I want to list.
Currently I'm forced to create a config for each device.

Thanks for the consideration.

**Comment by benct** [comment]
I've tried to have a look at incorporating some support for auto-entities or similar things in the past, but it is just too much work at the moment and I'm not even sure I'll be able to make it work. If someone makes a pull-request with something that might work I'll have a closer look at it, but for now I'm afraid I will not be implementing this.
