### ISSUE TITLE
Entity State Can No Longer be Set as Secondary Info

### ISSUE THREAD

**Issue by Jonah1970** [benct/lovelace-multiple-entity-row#79]
After upgrading to v3.2.0 I noticed that the state for my Z-wave nodes which I had as secondary info was now missing.  On the previous version the following config would display the state below the friendly name, I did this to improve the layout as some of the Z-wave states can be quite long e.g. "Initializing (CacheLoad)".

![image](https://user-images.githubusercontent.com/53110372/84200585-f8909100-aa9e-11ea-86f0-e4ad3e9c65d7.png)

It may be that this was never intended to work but I thought I would report it in case it is a bug.

Cheers!

**Comment by benct** [comment]
Is this still an issue? I cannot see why these states should not be displayed..

**Comment by Jonah1970** [comment]
I actually worked around the problem by displaying the state on the right hand side and the neighbours as secondary info as shown below:

![image](https://user-images.githubusercontent.com/53110372/96644650-435dc780-1321-11eb-8014-afc4744b4c9a.png)

As a test I went back to see whether the state could appear as secondary info as I originally had it - this now appears to be fine but I don't know when this got fixed (I am currently on version 0.116.3):

![image](https://user-images.githubusercontent.com/53110372/96644994-d3037600-1321-11eb-97b9-b29269f183b3.png)

I have therefore closed the issue.
