### ISSUE TITLE
the device_tracker.XXXX attribute,cann't show chinese.

### ISSUE THREAD

**Issue by xinhu808** [benct/lovelace-multiple-entity-row#80]
Since homeassistant 0.110.in lovelace-multiple-entity-row,the device_tracker.XXXX attribute,cann't show chinese‘在家(at home)’，just show 'home'.the map customize  location name if use chinese,can    show chinese.    thx.
![无标题](https://user-images.githubusercontent.com/32804301/84485092-3c1d1200-acce-11ea-8c8d-9782a9ba4576.png)

**Comment by benct** [comment]
I'm not sure what causes this. Is it still an issue?
