### ISSUE TITLE
Card background issue 

### ISSUE THREAD

**Issue by tibortiz** [benct/lovelace-multiple-entity-row#81]
Multiple entity row is the only card in my HA that don't have background and I don't know why :

I guess a screenshot is more explicit than words :)

![image](https://user-images.githubusercontent.com/25587210/84524732-b784c080-acda-11ea-9ee5-e656d8d42f5b.png)

**Comment by benct** [comment]
Looks like you do not use this card/plugin inside a standard [entities](https://www.home-assistant.io/lovelace/entities/) card? How does you config look?

**Comment by tibortiz** [comment]
Thanks a lot ! Work like charm now !

**Comment by andreas-bulling** [comment]
Can one of you provide a YAML example for how to do this? Thanks!
