### ISSUE TITLE
Feature Request - format template

### ISSUE THREAD

**Issue by mjhcdk** [benct/lovelace-multiple-entity-row#85]
Hi, 

Thank you for a sharing this awesome card - But wonder if it would be possible to use format templating when displaying entities. i.e. I have sensors showing temperature with 2 decimals (23.34 c ). I would like to display then as (23c or 23.4 c). I know I can create a "shadow" sensor with value_template, but it seems a bit cumbersome. 

Regards
Michael

**Comment by benct** [comment]
This would be added/supported with general templating support (see #35).
