### ISSUE TITLE
Problem view in tablet card

### ISSUE THREAD

**Issue by roberdlv** [benct/lovelace-multiple-entity-row#94]
Hello friends, I am trying to add several multiple row cards, on the computer and mobile phone they look good, but on the tablet they are cut, any solution to this?

https://community-assets.home-assistant.io/original/3X/b/3/b373df0940e9ed38e2869e3bc254e73d3989a3da.jpeg

Example code:

type: entities
show_header_toggle: false
entities:

entity: switch.enchufe_cocina_frigorifico
icon: ‘mdi:fridge-bottom’
type: ‘custom:multiple-entity-row’
name: Frigorifico
toggle: true
state_color: true
entities:
entity: sensor.potencia_frigorifico
name: Power
entity: sensor.energia_total_frigorifico
name: Total
type: section
entity: switch.enchufe_cocina_micro
icon: ‘mdi:microwave’
type: ‘custom:multiple-entity-row’
name: Microondas
toggle: true
state_color: true
entities:
entity: sensor.potencia_enchufe_micro
name: Power
entity: sensor.energia_total_enchufe_micro
name: Total
View in Pc is correct:

https://community-assets.home-assistant.io/original/3X/8/1/8129b92014d108034e842835f1a483d8871c0067.jpeg

**Comment by benct** [comment]
The columns are given too little horizontal spacing on your tablet, which squishes the content.. Unfortunately that isn't controlled by this card/plugin, but by the HA frontend framework. You could try adding all the entities in a single `entities` card and split them with `section`s instead, like shown in the [example](https://github.com/benct/lovelace-multiple-entity-row#examples).
