### ISSUE TITLE
Feature request: markdown row type

### ISSUE THREAD

**Issue by LupoCri** [benct/lovelace-multiple-entity-row#95]
Hi

I ask if is possible to insert in addition to the type '_section_' also the '_markdown_' (from [marked.js](https://www.home-assistant.io/lovelace/markdown/)).

Thanks for the wonderful work.
LupoCri

**Comment by benct** [comment]
I am not sure how (or why) to include markdown support in this card. There is little to no room to display markdown content in a single entity row. This card does not support section either, so I am a bit confused about what you are requesting. But the general answer would be no, I'm afraid markdown support will not be added.

Thank you for the compliment though!

**Comment by LupoCri** [comment]
Because to obtain a header like this: 

![movelace_markdown](https://user-images.githubusercontent.com/66326247/95554559-a80b4f00-0a10-11eb-8f09-22d2275b1d48.png)

Tnx,
LupoCri
