### ISSUE TITLE
custom element doesnt exist

### ISSUE THREAD

**Issue by geltzer** [benct/lovelace-multiple-entity-row#99]
after installing the card as described in the install art of the documentation adn trying to copy the example code. i keep getting the error: Custom element doesn't exist: multiple-entity-row. its not the sensors missing its complaining about, but the card itself.
ive tried installing it both manually and via hacs

![Unavngivet](https://user-images.githubusercontent.com/64040343/93929827-bec95a80-fd1c-11ea-892d-ac5cda1df151.jpg)

**Comment by benct** [comment]
What version are you on? Does it work in any other browsers? Are there any errors in the browser console window (F12)?
